-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Grammar.Object.Grammars_min_fields exposing (..)

import Grammar.InputObject
import Grammar.Interface
import Grammar.Object
import Grammar.Scalar
import Grammar.ScalarCodecs
import Grammar.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


description : SelectionSet (Maybe String) Grammar.Object.Grammars_min_fields
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


grammar : SelectionSet (Maybe String) Grammar.Object.Grammars_min_fields
grammar =
    Object.selectionForField "(Maybe String)" "grammar" [] (Decode.string |> Decode.nullable)


name : SelectionSet (Maybe String) Grammar.Object.Grammars_min_fields
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)
