-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Grammar.Object.Grammars_aggregate exposing (..)

import Grammar.InputObject
import Grammar.Interface
import Grammar.Object
import Grammar.Scalar
import Grammar.ScalarCodecs
import Grammar.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


aggregate : SelectionSet decodesTo Grammar.Object.Grammars_aggregate_fields -> SelectionSet (Maybe decodesTo) Grammar.Object.Grammars_aggregate
aggregate object_ =
    Object.selectionForCompositeField "aggregate" [] object_ (identity >> Decode.nullable)


nodes : SelectionSet decodesTo Grammar.Object.Grammars -> SelectionSet (List decodesTo) Grammar.Object.Grammars_aggregate
nodes object_ =
    Object.selectionForCompositeField "nodes" [] object_ (identity >> Decode.list)
