-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Grammar.Object.Grammars exposing (..)

import Grammar.InputObject
import Grammar.Interface
import Grammar.Object
import Grammar.Scalar
import Grammar.ScalarCodecs
import Grammar.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


description : SelectionSet (Maybe String) Grammar.Object.Grammars
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


grammar : SelectionSet String Grammar.Object.Grammars
grammar =
    Object.selectionForField "String" "grammar" [] Decode.string


id : SelectionSet Grammar.ScalarCodecs.Uuid Grammar.Object.Grammars
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (Grammar.ScalarCodecs.codecs |> Grammar.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


name : SelectionSet String Grammar.Object.Grammars
name =
    Object.selectionForField "String" "name" [] Decode.string


parent : SelectionSet Grammar.ScalarCodecs.Uuid Grammar.Object.Grammars
parent =
    Object.selectionForField "ScalarCodecs.Uuid" "parent" [] (Grammar.ScalarCodecs.codecs |> Grammar.Scalar.unwrapCodecs |> .codecUuid |> .decoder)
