-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Grammar.Object exposing (..)


type Grammars
    = Grammars


type Grammars_aggregate
    = Grammars_aggregate


type Grammars_aggregate_fields
    = Grammars_aggregate_fields


type Grammars_max_fields
    = Grammars_max_fields


type Grammars_min_fields
    = Grammars_min_fields


type Grammars_mutation_response
    = Grammars_mutation_response
