-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Grammar.ScalarCodecs exposing (..)

import Grammar.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Grammar.Scalar.Id


type alias Uuid =
    Grammar.Scalar.Uuid


codecs : Grammar.Scalar.Codecs Id Uuid
codecs =
    Grammar.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecUuid = defaultCodecs.codecUuid
        }
