-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Grammar.Enum.Grammars_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "grammars"

  - Grammars\_pkey - unique or primary key constraint

-}
type Grammars_constraint
    = Grammars_pkey


list : List Grammars_constraint
list =
    [ Grammars_pkey ]


decoder : Decoder Grammars_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "grammars_pkey" ->
                        Decode.succeed Grammars_pkey

                    _ ->
                        Decode.fail ("Invalid Grammars_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Grammars_constraint -> String
toString enum =
    case enum of
        Grammars_pkey ->
            "grammars_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Grammars_constraint
fromString enumString =
    case enumString of
        "grammars_pkey" ->
            Just Grammars_pkey

        _ ->
            Nothing
